
#Generated Form Function
function GenerateForm {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.8.0
    # Generated On: 7/3/2011 11:35 AM
    # Generated By: sean.kearney
    ########################################################################

    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname(“System.Windows.Forms”) | Out-Null
    [reflection.assembly]::loadwithpartialname(“System.Drawing”) | Out-Null
    #endregion

    #region Generated Form Objects
    $IPForm = New-Object System.Windows.Forms.Form
    $IPButton = New-Object System.Windows.Forms.Button
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects

    #———————————————-
    #Generated Event Script Blocks
    #———————————————-
    #Provide Custom Code for events specified in PrimalForms.
    $handler_UnlockAccountButton_Click=
    {
    #TODO: Place custom script here

    }

    $OnLoadForm_StateCorrection=
    {#Correct the initial state of the form to prevent the .Net maximized form issue
    $IPForm.WindowState = $InitialFormWindowState
    }

    #———————————————-
    #region Generated Form Code
    $IPForm.Text = “IPSee”
    $IPForm.Name = “IPSee”
    $IPForm.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Width = 265
    $System_Drawing_Size.Height = 55
    $IPForm.ClientSize = $System_Drawing_Size

    $IPButton.TabIndex = 0
    $IPButton.Name = “IPInfo”
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Width = 240
    $System_Drawing_Size.Height = 23
    $IPButton.Size = $System_Drawing_Size
    $IPButton.UseVisualStyleBackColor = $True

    $IPButton.Text = “IP Lookup”

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 13
    $IPButton.Location = $System_Drawing_Point
    $IPButton.DataBindings.DefaultDataSourceUpdateMode = 0
    $IPButton.add_Click($handler_UnlockAccountButton_Click)

    $IPForm.Controls.Add($IPButton)

    #endregion Generated Form Code

    #Save the initial state of the form
    $InitialFormWindowState = $IPForm.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $IPForm.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $IPForm.ShowDialog()| Out-Null

    } #End Function

    #Call the Function
    GenerateForm